### ISSUE TITLE
winding backwards?

### ISSUE THREAD

**Issue by donbright** [virtualritz/polyhedron-operators#20]
The winding/ordering of the faces appears to possibly be backwards. The standard for OpenGL, viewed from outside of a polyhedron, is for the winding of faces to be counter-clockwise (anti-clockwise). However the polyhedra are being generated with the winding, viewed from outside the object, to be clockwise. This is visible in meshlab for example. 

This causes the 'normals' for the faces to be pointing inwards by default rather than outwards as is likely intended. 

For example on the cube the face between the points 0 1 2 3 is listed as 1,3,2,0 which gives the winding, viewed from outside the cube, as clockwise. Meshlab interprets the normals as pointing inside and is why all the faces look dark gray. 

![winding](https://github.com/virtualritz/polyhedron-ops/assets/896858/315fbc9e-aea6-4d2f-9177-b146698210a1)

![cube](https://github.com/virtualritz/polyhedron-ops/assets/896858/727e7b54-b994-40c3-8968-b8a563bca1a1)

The OBJ format spec from Wavefront , linked off wikipedia, also appears to indicate counter-clockwise. http://fegemo.github.io/cefet-cg/attachments/obj-spec.pdf

i have a change in the works to make all polyhedron faces counter-clockwise but wanted to check first and have this issue as reference. 

thanks

**Comment by virtualritz** [comment]
Winding usually has three variables:
- Which one is considered facing in the modeling app, clockwise or counterclockwise.
- Coordinate system, left-handed or right-handed.
- Interpretation of both by the target renderer.

My experience from 30+ years in CG is that your mileage with all the above my vary. 😅

That's why the `Polyhedron::write_obj()` function has a `reverse_winding` flag.
And why `Polyhedron::reverse()` exists.

I'm happy though to flip the default in that function. I.e. swap lines 43 & 52 in `src/io/write_obj()`. That would presumably have the desired effect?

I have not seen any issue importing the OBJs from the playground into Wings3D though.

**Comment by virtualritz** [comment]
If you had in mind changing the winding in general (i.e. at the code site where primitives are defined), that is also fine with me.

Basically, I do not care what the internal winding is. All I care about is that stuff works as smooth as possible for a user of the crate in the most number of cases.

**Comment by donbright** [comment]
thanks!! i didnt know. 

i shall leave the default as is

**Comment by virtualritz** [comment]
I'm looking forward to your PR btw. I peeked into your fork. 😁
